name: pet_vet_project
description: "Pet Vet Project"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  build_runner: ^2.4.11
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  intl: ^0.19.0
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0


flutter_icons:
  android: true
  ios: true
  web: 
    generate: true
    image_path: "assets/images/logo.png"
  image_path: "assets/images/logo.png"



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500  




  

  assets:
    - assets/images/
    - assets/translations/
